### ISSUE TITLE
Fix Excel export with multi-index columns

### ISSUE THREAD

**Issue by kasnerz** [kasnerz/tabgenie#18]
For some tables (supposedly with hierarchical headers), export to XLSX does not work.

**To replicate:**

in web interface go to _HiTab - dev - table 1277 → export to XLSX_
```
  File "/home/kasner/virtualenv/tabgenie/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 578, in _format_header_mi
    raise NotImplementedError(
NotImplementedError: Writing to Excel with MultiIndex columns and no index ('index'=False) is not yet implemented.
```

**Comment by kategerasimenko** [comment]
I can take it.

**Comment by kategerasimenko** [comment]
This exact problem can be fixed but there's general problem with pandas when handling merged cells. The table with merged cells (HiTab dev 1277) looks like this in csv/excel:

|   club             |   season   |   division         |   league  |   league  |   fa cup  |   fa cup  |   other  |   other  |   total  |   total  |
|--------------------|------------|--------------------|-----------|-----------|-----------|-----------|----------|----------|----------|----------|
|   club             |   season   |   division         |   apps    |   goals   |   apps    |   goals   |   apps   |   goals  |   apps   |   goals  |
|   chester city     |   1987-88  |   third division   |   1       |   0       |   0       |   0       |   0      |   0      |   1      |   0      |
|   chester city     |   1988-89  |   third division   |   25      |   2       |   0       |   0       |   5      |   0      |   30     |   2      |
|   chester city     |   1989-90  |   third division   |   18      |   4       |   2       |   0       |   6      |   1      |   26     |   5      |
|   chester city     |   total    |   total            |   44      |   6       |   2       |   0       |   11     |   1      |   57     |   7      |
|   tranmere rovers  |   1993-94  |   first division   |   0       |   0       |   0       |   0       |   0      |   0      |   0      |   0      |
|   port vale        |   1993-94  |   second division  |   2       |   0       |   1       |   0       |   0      |   0      |   3      |   0      |
