### ISSUE TITLE
Add about infobox

### ISSUE THREAD

**Issue by kasnerz** [kasnerz/tabgenie#22]
The "About" button is currently just a placeholder.

The button should displaying a small infobox or infobubble with information about the authors and the project.

**Comment by MostlyGenius** [comment]
Can you assign this issue to me?

**Comment by kasnerz** [comment]
> Can you assign this issue to me?

Hi, do you want to contribute to the project in general? 

We are currently developing it only within our research group, so I am not sure if this is a good first issue for you in particular.

However, we will welcome any external contributions once the project is made public, which is going to happen in ~1-2 months.

**Comment by kasnerz** [comment]
Solved in 96803f3ac983b6cb78aa6ff5a0cbd79ad49ff48e
