### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by kasnerz** [kasnerz/tabgenie#34]
- [x] hide the less important table properties and display them on demand (using a collapsible block)
- [x] remove the switches for pipelines and outputs in the left panel, unify them with the output boxes in the right panel (the switch will be just a small button available at the related output box)
- [x] integrate the pipeline switches with pipeline setttings: e.g. add a small cogwheel at the top of the output box

**Comment by tuetschek** [comment]
- [ ] Get rid of the horizontal scrollbar 😁 (if it's not too hard to do)

**Comment by kasnerz** [comment]
@tuetschek Can you attach a screenshot where you have it? I see it only for the tables which do not fit the screen horizontally (and I think it's good to have it in these cases).

**Comment by tuetschek** [comment]
@kasnerz sure – here it is :-) 
![image](https://user-images.githubusercontent.com/2931158/216060710-97f5c36f-0f16-4159-b684-e99eac666778.png)

Not sure what the problem is, maybe it's OS-related? I can see the scrollbar both in Firefox and Chrome.

**Comment by kasnerz** [comment]
@tuetschek Fixed in 5831595104d7d588c94f632eb70e22a4cd575430

**Comment by tuetschek** [comment]
@kasnerz awesome, thank you 😍!
