### ISSUE TITLE
Allow to specify huggingface cache in other directory instead of ~/.cache/huggingface

### ISSUE THREAD

**Issue by oplatek** [kasnerz/tabgenie#56]

**Comment by kasnerz** [comment]
This is being done with the environment variable `HF_DATASETS_CACHE` (see https://huggingface.co/docs/datasets/cache ). 

I agree that we can add it to the config file and modify it from within the program with `os.environ`.

**Comment by oplatek** [comment]
Cool, I think it is enough to mention this in the docs.
