### ISSUE TITLE
do not store datasets/splits in to app.config

### ISSUE THREAD

**Issue by oplatek** [kasnerz/tabgenie#68]
If app.config is changed the app reloads in debug model
IMO the app.config is intended to be persistent.

Currently, it breaks using flask sessions in development server with auto-reloading.
Auto reloading means that new session and new secret key is used.

**Comment by kasnerz** [comment]
Should be solved by 10dd7bcb61b1f4404ce6c3d2488fcf1951442ccd , feel free to re-open if not
