### ISSUE TITLE
Potential bugs in the datasets

### ISSUE THREAD

**Issue by kategerasimenko** [kasnerz/tabgenie#82]
This is the list of the things that I found weird and will need double-checking.

- [x] scigen - text and reference confused?
- [x] scigen - for values in bold, _h object in cell value, error when linearizing
- [x] numericnlg - refs don't look like refs
- [ ] logic2text - look into the highlights provided by `contlog`
- [x] logicnlg - restore the highlights, add disclaimer
- [x] hitab train 66 - error
- [x] sportsett - why first three cols empty? upd: fixed by #78

**Comment by kasnerz** [comment]
Also some datasets are currently showing empty tables (at least on quest), putting a note here to myself to investigate it.

**Comment by kategerasimenko** [comment]
@kasnerz empty cells are fixed by #78  :)

**Comment by kategerasimenko** [comment]
@kasnerz numericnlg is not fully uploaded to HF hub - reference field is missing. Should we omit this df for now?

**Comment by kasnerz** [comment]
@kategerasimenko You're right! For NumericNLG I included just table captions but there were also files containing related descriptions and a few extra fields. I fixed it on HF and in a15652f9c50468f413ec8dade6f75501309308a3

**Comment by kategerasimenko** [comment]
logic2text is separate issue #112 now, everything else is fixed, closing
