### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by kategerasimenko** [kasnerz/tabgenie#97]
- [x] in the table navigation block, the elements with table numbers have larger height than buttons
- [x] show notes themselves (at least the beginning) in the notes list
- [x] fix the key column width for properties (now it changes dynamically when toggling the individual properties)
- [x] the button for regenerating the model output in the interactive mode is too small - change to "Regenerate output" button in the pipeline output box
- [x] in "toggle view", do we need the view only with pre-generated outputs? is it needed without looking at input data?
- [x] think of better json structure in the export
- [x] clickable email addresses in the about section?
- [x] "export examples with notes" doesn't include notes into the files
- [x] for datasets without header (eg e2e), dummy header is inserted when exporting to csv
- [x] mobile version? :)

**Comment by kasnerz** [comment]
>  in "toggle view", do we need the view only with pre-generated outputs? is it needed without looking at input data?

I think it's nice to have a full screen view for some outputs - for example the graph can get very large and you may want to examine it in detail ;) 

I agree with the rest of the points.

**Comment by kasnerz** [comment]
> clickable email addresses in the about section?

Wontfix, every prevented spam e-mail counts :grin: https://www.quora.com/How-effective-is-obfuscating-an-email-address-by-replacing-symbols-with-words-e-g-AT-instead-of-at-preventing-spam
